services:
  fitnessapp:
    build:
      context: .
      dockerfile: FitnessApp.Server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - SEED_DEMO_DATA=true
