// <auto-generated />
using System;
using FitnessApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816131150_AddRankTracking")]
    partial class AddRankTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FitnessApp.Server.Models.FitnessActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.HasIndex("UserId");

                    b.ToTable("FitnessActivities");
                });

            modelBuilder.Entity("FitnessApp.Server.Models.RankChangeEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Delta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("RankChangeEvents");
                });

            modelBuilder.Entity("FitnessApp.Server.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsPerUnit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MetricType = 0,
                            Name = "running",
                            PointsPerUnit = 100m
                        },
                        new
                        {
                            Id = 2,
                            MetricType = 0,
                            Name = "walking",
                            PointsPerUnit = 50m
                        },
                        new
                        {
                            Id = 3,
                            MetricType = 0,
                            Name = "cycling",
                            PointsPerUnit = 25m
                        },
                        new
                        {
                            Id = 4,
                            MetricType = 1,
                            Name = "gym",
                            PointsPerUnit = 5m
                        },
                        new
                        {
                            Id = 5,
                            MetricType = 1,
                            Name = "swimming",
                            PointsPerUnit = 15m
                        },
                        new
                        {
                            Id = 6,
                            MetricType = 2,
                            Name = "daily_steps",
                            PointsPerUnit = 1m
                        });
                });

            modelBuilder.Entity("FitnessApp.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFullName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessApp.Server.Models.FitnessActivity", b =>
                {
                    b.HasOne("FitnessApp.Server.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Server.Models.RankChangeEvent", b =>
                {
                    b.HasOne("FitnessApp.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
